name: ci/cd
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: login into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build and push docker image
        run: |
           docker build -t samba1232/img2 .
           docker push samba1232/img2
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: installing eksctl
        uses: jakejarvis/eksctl-action@v1
        with:
          version: latest
      - name: installing kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.0
      - name: creating cluster
        run: |
          eksctl create cluster --name netflix-cluster --version 1.27 --region ap-southeast-2 \
          --nodegroup-name standard-workers --node-type t3.micro --nodes 1 --nodes-min 1 --nodes-max 1 --managed
      - name: deploy to eks
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml

    
