name: ci/cd
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: login into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build and push docker image
        run: |
           docker build -t samba1232/img2 .
           docker push samba1232/img2
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ap-southeast-2

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.106.0/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
      - name: installing kubernetes
        uses: azure/setup-kubectl@v3
        with: 
          version: 'v1.27.0'
      - name: creating cluster
        run: |
          eksctl create cluster --name zenistu1-cluster --version 1.28 --region ap-southeast-2 \
          --nodegroup-name standard-workers --node-type t3.micro --nodes 1 --nodes-min 1 --nodes-max 1 --managed
      - name: deploy to eks
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          kubectl rollout status deployment netflix

    
